use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use image::imageops::FilterType;
use image::{Rgba, RgbaImage};

const AVATAR_COUNT: usize = 8;
const CANVAS_W: u32 = 96;
const CANVAS_H: u32 = 72;
const PALETTE_LIMIT: usize = 256;
const ALPHA_CUTOFF: u8 = 32;
const PREVIEW_SCALE: u32 = 3;
const WALK_SEQUENCE_FRAMES: usize = 5;
const WALK_POSES: usize = 4;
const MARKET_SEQUENCE_FRAMES: usize = 9;
const STATUS_SEQUENCE_FRAMES: usize = 16;
const COMBAT_SEQUENCE_FRAMES: usize = 19;
const STAND_POSES: usize = 3;
const CLIMB_POSES: usize = 2;
const STAND2_POSES: usize = 3;
const SIT_POSES: usize = 1;
const ALERT_POSES: usize = 3;
const SWING_POSES: usize = 3;
const COMBAT_CANVAS_W: u32 = CANVAS_W * 2;
const COMBAT_CANVAS_H: u32 = CANVAS_H * 2;
const MAGIC_CLAW_CANVAS_W: u32 = 96;
const MAGIC_CLAW_CANVAS_H: u32 = 96;
const MAGIC_CLAW_CANVAS_ORIGIN_X: u32 = 48;
const MAGIC_CLAW_CANVAS_ORIGIN_Y: u32 = 82;
const MAGIC_CLAW_FRAME_SIZES: [(u32, u32); 4] = [(87, 87), (73, 79), (63, 79), (56, 77)];
const MAGIC_CLAW_ORIGINS: [(u32, u32); 4] = [(43, 73), (39, 69), (39, 69), (39, 69)];
const BODY_CROP_PAD_X: u32 = 8;
const BODY_CROP_PAD_TOP: u32 = 4;
const BODY_CROP_HALF_WINDOW: u32 = 52;
const BODY_CROP_MAX_WIDTH: u32 = 104;
const BODY_CROP_MAX_HEIGHT: u32 = 112;
const EFFECT_HEAVY_MIN_WIDTH: u32 = 100;
const EFFECT_HEAVY_MIN_HEIGHT: u32 = 120;
const EFFECT_HEAVY_CROP_WIDTH: u32 = 68;
const EFFECT_HEAVY_CROP_HEIGHT: u32 = 86;
const BODY_FOOT_HALF_WINDOW: u32 = 16;
const STATIC_PALETTE_HEADER: &str =
    "# Local-only NEXON ranking high-resolution paperdoll colors generated by avatar_quantize.\n";
const WALK_PALETTE_HEADER: &str =
    "# Local-only NEXON Open API stand1/walk1 colors generated by avatar_quantize.\n";
const MARKET_PALETTE_HEADER: &str =
    "# Local-only NEXON Open API stand1/walk1/ladder colors generated by avatar_quantize.\n";
const STATUS_PALETTE_HEADER: &str = "# Local-only NEXON Open API stand1/walk1/ladder/stand2/sit/alert colors generated by avatar_quantize.\n";

#[derive(Clone, Copy, Debug)]
struct Bucket {
    key: [u8; 3],
    rgb: [f64; 3],
    count: u64,
}

struct QuantizedPalette {
    keys: Vec<char>,
    colors: Vec<[u8; 3]>,
    centroids: Vec<[f64; 3]>,
}

#[derive(Clone, Copy)]
struct ImageTransform {
    crop_x: u32,
    crop_y: u32,
    crop_w: u32,
    crop_h: u32,
    target_w: u32,
    target_h: u32,
    offset_x: u32,
    offset_y: u32,
}

impl ImageTransform {
    fn from_bounds(min_x: u32, min_y: u32, max_x: u32, max_y: u32) -> Self {
        let crop_w = max_x - min_x + 1;
        let crop_h = max_y - min_y + 1;
        let fit = f64::min(
            CANVAS_W as f64 / crop_w as f64,
            CANVAS_H as f64 / crop_h as f64,
        );
        let target_w = ((crop_w as f64 * fit).round() as u32).clamp(1, CANVAS_W);
        let target_h = ((crop_h as f64 * fit).round() as u32).clamp(1, CANVAS_H);
        Self {
            crop_x: min_x,
            crop_y: min_y,
            crop_w,
            crop_h,
            target_w,
            target_h,
            offset_x: (CANVAS_W - target_w) / 2,
            offset_y: CANVAS_H - target_h,
        }
    }
}

#[derive(Clone, Copy)]
enum QuantizeMode {
    Static,
    WalkCycle,
    MarketCycle,
    StatusCycle,
    CombatCycle,
    SkillEffect,
}

impl QuantizeMode {
    fn expected_inputs(self) -> usize {
        match self {
            Self::Static => AVATAR_COUNT,
            Self::WalkCycle => AVATAR_COUNT * WALK_SEQUENCE_FRAMES,
            Self::MarketCycle => AVATAR_COUNT * MARKET_SEQUENCE_FRAMES,
            Self::StatusCycle => AVATAR_COUNT * STATUS_SEQUENCE_FRAMES,
            Self::CombatCycle => AVATAR_COUNT * COMBAT_SEQUENCE_FRAMES,
            Self::SkillEffect => MAGIC_CLAW_FRAME_SIZES.len(),
        }
    }
}

struct OutputLayout {
    root: PathBuf,
    preview: PathBuf,
}

struct SpriteOutput<'a> {
    source: &'a Path,
    image: &'a RgbaImage,
    stem: String,
}

#[derive(Clone, Copy)]
struct ActionOutputSpec {
    input_offset: usize,
    poses: usize,
    stem_prefix: &'static str,
}

const MARKET_ACTION_OUTPUTS: [ActionOutputSpec; 3] = [
    ActionOutputSpec {
        input_offset: 0,
        poses: STAND_POSES,
        stem_prefix: "market_avatar_stand_hires",
    },
    ActionOutputSpec {
        input_offset: STAND_POSES,
        poses: WALK_POSES,
        stem_prefix: "market_avatar_walk_hires",
    },
    ActionOutputSpec {
        input_offset: STAND_POSES + WALK_POSES,
        poses: CLIMB_POSES,
        stem_prefix: "market_avatar_climb_hires",
    },
];

const STATUS_ACTION_OUTPUTS: [ActionOutputSpec; 6] = [
    MARKET_ACTION_OUTPUTS[0],
    MARKET_ACTION_OUTPUTS[1],
    MARKET_ACTION_OUTPUTS[2],
    ActionOutputSpec {
        input_offset: STAND_POSES + WALK_POSES + CLIMB_POSES,
        poses: STAND2_POSES,
        stem_prefix: "market_avatar_stand2_hires",
    },
    ActionOutputSpec {
        input_offset: STAND_POSES + WALK_POSES + CLIMB_POSES + STAND2_POSES,
        poses: SIT_POSES,
        stem_prefix: "market_avatar_sit_hires",
    },
    ActionOutputSpec {
        input_offset: STAND_POSES + WALK_POSES + CLIMB_POSES + STAND2_POSES + SIT_POSES,
        poses: ALERT_POSES,
        stem_prefix: "market_avatar_alert_hires",
    },
];

const COMBAT_SWING_OUTPUT: ActionOutputSpec = ActionOutputSpec {
    input_offset: STATUS_SEQUENCE_FRAMES,
    poses: SWING_POSES,
    stem_prefix: "training_avatar_attack_hires",
};

struct OutputBatch<'a> {
    layout: &'a OutputLayout,
    inputs: &'a [PathBuf],
    images: &'a [RgbaImage],
    palette: &'a QuantizedPalette,
}

impl OutputBatch<'_> {
    fn write_base(&self, slot: usize, sequence_start: usize) -> Result<()> {
        write_sprite_output(
            self.layout,
            SpriteOutput {
                source: &self.inputs[sequence_start],
                image: &self.images[sequence_start],
                stem: format!("market_avatar_hires_{slot}"),
            },
            self.palette,
        )
    }

    fn write_action(
        &self,
        slot: usize,
        sequence_start: usize,
        action: ActionOutputSpec,
    ) -> Result<()> {
        for pose in 0..action.poses {
            let input_index = sequence_start + action.input_offset + pose;
            write_sprite_output(
                self.layout,
                SpriteOutput {
                    source: &self.inputs[input_index],
                    image: &self.images[input_index],
                    stem: format!("{}_{}", action.stem_prefix, slot * action.poses + pose),
                },
                self.palette,
            )?;
        }
        Ok(())
    }
}

fn distance_sq(a: [f64; 3], b: [f64; 3]) -> f64 {
    let dr = a[0] - b[0];
    let dg = a[1] - b[1];
    let db = a[2] - b[2];
    dr * dr * 0.9 + dg * dg * 1.2 + db * db * 0.8
}

fn nearest(rgb: [f64; 3], centroids: &[[f64; 3]]) -> usize {
    centroids
        .iter()
        .enumerate()
        .min_by(|(_, a), (_, b)| {
            distance_sq(rgb, **a)
                .partial_cmp(&distance_sq(rgb, **b))
                .expect("finite RGB distances")
        })
        .map(|(index, _)| index)
        .expect("at least one centroid")
}

fn initial_centroids(buckets: &[Bucket], count: usize) -> Vec<[f64; 3]> {
    let mut out = vec![buckets[0].rgb];
    while out.len() < count {
        let next = buckets
            .iter()
            .max_by(|a, b| {
                let score = |bucket: &Bucket| {
                    let novelty = out
                        .iter()
                        .map(|center| distance_sq(bucket.rgb, *center))
                        .fold(f64::INFINITY, f64::min);
                    novelty * (bucket.count as f64).sqrt()
                };
                score(a)
                    .partial_cmp(&score(b))
                    .expect("finite centroid scores")
            })
            .expect("non-empty histogram");
        out.push(next.rgb);
    }
    out
}

fn alpha_bounds(image: &RgbaImage) -> Option<(u32, u32, u32, u32)> {
    let mut min_x = image.width();
    let mut min_y = image.height();
    let mut max_x = 0;
    let mut max_y = 0;
    let mut found = false;
    for (x, y, pixel) in image.enumerate_pixels() {
        if pixel[3] < ALPHA_CUTOFF {
            continue;
        }
        found = true;
        min_x = min_x.min(x);
        min_y = min_y.min(y);
        max_x = max_x.max(x);
        max_y = max_y.max(y);
    }
    found.then_some((min_x, min_y, max_x, max_y))
}

fn normalize_avatar(source: &RgbaImage) -> Result<RgbaImage> {
    let (min_x, min_y, max_x, max_y) = alpha_bounds(source).context("avatar is transparent")?;
    Ok(apply_transform(
        source,
        ImageTransform::from_bounds(min_x, min_y, max_x, max_y),
    ))
}

fn body_focused_bounds(image: &RgbaImage) -> Option<(u32, u32, u32, u32)> {
    let centre_x = image.width() / 2;
    let window_min_x = centre_x.saturating_sub(BODY_CROP_HALF_WINDOW);
    let window_max_x = centre_x
        .saturating_add(BODY_CROP_HALF_WINDOW)
        .min(image.width().saturating_sub(1));
    let mut min_x = image.width();
    let mut min_y = image.height();
    let mut max_x = 0;
    let mut max_y = 0;
    let mut found = false;
    for (x, y, pixel) in image.enumerate_pixels() {
        if x < window_min_x || x > window_max_x || pixel[3] < ALPHA_CUTOFF {
            continue;
        }
        found = true;
        min_x = min_x.min(x);
        min_y = min_y.min(y);
        max_x = max_x.max(x);
        max_y = max_y.max(y);
    }
    if !found {
        return alpha_bounds(image);
    }

    min_x = min_x.saturating_sub(BODY_CROP_PAD_X);
    max_x = max_x
        .saturating_add(BODY_CROP_PAD_X)
        .min(image.width().saturating_sub(1));
    min_y = min_y.saturating_sub(BODY_CROP_PAD_TOP);

    if max_x - min_x + 1 > BODY_CROP_MAX_WIDTH {
        let body_centre = (min_x + max_x) / 2;
        min_x = body_centre.saturating_sub(BODY_CROP_MAX_WIDTH / 2);
        max_x = min_x
            .saturating_add(BODY_CROP_MAX_WIDTH - 1)
            .min(image.width().saturating_sub(1));
        min_x = max_x.saturating_add(1).saturating_sub(BODY_CROP_MAX_WIDTH);
    }
    if max_y - min_y + 1 > BODY_CROP_MAX_HEIGHT {
        min_y = max_y.saturating_add(1).saturating_sub(BODY_CROP_MAX_HEIGHT);
    }
    Some((min_x, min_y, max_x, max_y))
}

fn sequence_transform(sources: &[RgbaImage]) -> Result<ImageTransform> {
    let stand = sources.first().context("avatar sequence is empty")?;
    for source in sources {
        if source.dimensions() != stand.dimensions() {
            bail!(
                "avatar sequence dimensions differ: expected {:?}, got {:?}",
                stand.dimensions(),
                source.dimensions()
            );
        }
    }
    let (full_min_x, full_min_y, full_max_x, full_max_y) =
        alpha_bounds(stand).context("standing avatar is transparent")?;
    let full_width = full_max_x - full_min_x + 1;
    let full_height = full_max_y - full_min_y + 1;
    if full_width > EFFECT_HEAVY_MIN_WIDTH || full_height > EFFECT_HEAVY_MIN_HEIGHT {
        let centre_x = stand.width() / 2;
        let min_x = centre_x.saturating_sub(EFFECT_HEAVY_CROP_WIDTH / 2);
        let max_x = min_x
            .saturating_add(EFFECT_HEAVY_CROP_WIDTH - 1)
            .min(stand.width().saturating_sub(1));
        let min_x = max_x
            .saturating_add(1)
            .saturating_sub(EFFECT_HEAVY_CROP_WIDTH);
        let foot_min_x = centre_x.saturating_sub(BODY_FOOT_HALF_WINDOW);
        let foot_max_x = centre_x
            .saturating_add(BODY_FOOT_HALF_WINDOW)
            .min(stand.width().saturating_sub(1));
        let max_y = sources
            .iter()
            .flat_map(|source| source.enumerate_pixels())
            .filter(|(x, y, pixel)| {
                *x >= foot_min_x
                    && *x <= foot_max_x
                    && *y >= stand.height() / 3
                    && pixel[3] >= ALPHA_CUTOFF
            })
            .map(|(_, y, _)| y)
            .max()
            .context("effect-heavy avatar has no opaque character foot corridor")?;
        let min_y = max_y
            .saturating_add(1)
            .saturating_sub(EFFECT_HEAVY_CROP_HEIGHT);
        return Ok(ImageTransform::from_bounds(min_x, min_y, max_x, max_y));
    }

    let (stand_min_x, stand_min_y, stand_max_x, stand_max_y) =
        body_focused_bounds(stand).context("standing avatar is transparent")?;
    let min_x = stand_min_x;
    let max_x = stand_max_x;
    let mut min_y = stand_min_y;
    let mut max_y = stand_max_y;

    for source in sources {
        for (x, y, pixel) in source.enumerate_pixels() {
            if x >= min_x && x <= max_x && pixel[3] >= ALPHA_CUTOFF {
                min_y = min_y.min(y);
                max_y = max_y.max(y);
            }
        }
    }
    Ok(ImageTransform::from_bounds(min_x, min_y, max_x, max_y))
}

fn apply_transform(source: &RgbaImage, transform: ImageTransform) -> RgbaImage {
    let cropped = image::imageops::crop_imm(
        source,
        transform.crop_x,
        transform.crop_y,
        transform.crop_w,
        transform.crop_h,
    )
    .to_image();
    let resized = image::imageops::resize(
        &cropped,
        transform.target_w,
        transform.target_h,
        FilterType::Nearest,
    );
    let mut canvas = RgbaImage::from_pixel(CANVAS_W, CANVAS_H, Rgba([0, 0, 0, 0]));
    for (x, y, pixel) in resized.enumerate_pixels() {
        canvas.put_pixel(transform.offset_x + x, transform.offset_y + y, *pixel);
    }
    canvas
}

/// Apply the established body transform to the full official attack render on
/// a 2x canvas.  The ordinary 96x72 character region sits bottom-centred inside
/// it, so replacing a stand frame with an attack frame cannot resize the body;
/// only weapon/skill pixels may extend into the extra transparent margins.
fn apply_combat_transform(source: &RgbaImage, transform: ImageTransform) -> RgbaImage {
    let scale_x = transform.target_w as f64 / transform.crop_w as f64;
    let scale_y = transform.target_h as f64 / transform.crop_h as f64;
    let scaled_w = ((source.width() as f64 * scale_x).round() as u32).max(1);
    let scaled_h = ((source.height() as f64 * scale_y).round() as u32).max(1);
    let scaled = image::imageops::resize(source, scaled_w, scaled_h, FilterType::Nearest);
    let body_left = (COMBAT_CANVAS_W - CANVAS_W) / 2;
    let body_top = COMBAT_CANVAS_H - CANVAS_H;
    let x = i64::from(body_left + transform.offset_x)
        - (transform.crop_x as f64 * scale_x).round() as i64;
    let y = i64::from(body_top + transform.offset_y)
        - (transform.crop_y as f64 * scale_y).round() as i64;
    let mut canvas = RgbaImage::from_pixel(COMBAT_CANVAS_W, COMBAT_CANVAS_H, Rgba([0, 0, 0, 0]));
    image::imageops::overlay(&mut canvas, &scaled, x, y);
    canvas
}

fn normalize_avatar_sequence(sources: &[RgbaImage]) -> Result<Vec<RgbaImage>> {
    let transform = sequence_transform(sources)?;
    sources
        .iter()
        .map(|source| apply_transform(source, transform))
        .map(Ok)
        .collect()
}

fn normalize_combat_sequence(sources: &[RgbaImage]) -> Result<Vec<RgbaImage>> {
    let (status, attacks) = sources.split_at(STATUS_SEQUENCE_FRAMES);
    let transform = sequence_transform(status)?;
    let mut normalized = status
        .iter()
        .map(|source| apply_transform(source, transform))
        .collect::<Vec<_>>();
    normalized.extend(
        attacks
            .iter()
            .map(|source| apply_combat_transform(source, transform)),
    );
    Ok(normalized)
}

fn avatar_palette_keys(count: usize) -> Vec<char> {
    (0..count)
        .map(|index| {
            char::from_u32(0x0200 + index as u32)
                .expect("the dedicated high-resolution palette range contains enough keys")
        })
        .collect()
}

fn sorted_buckets(histogram: HashMap<[u8; 3], ([u64; 3], u64)>) -> Vec<Bucket> {
    let mut buckets = histogram
        .into_iter()
        .map(|(key, (sum, count))| Bucket {
            key,
            rgb: [
                sum[0] as f64 / count as f64,
                sum[1] as f64 / count as f64,
                sum[2] as f64 / count as f64,
            ],
            count,
        })
        .collect::<Vec<_>>();
    buckets.sort_by(|a, b| b.count.cmp(&a.count).then_with(|| a.key.cmp(&b.key)));
    buckets
}

fn quantize(images: &[RgbaImage]) -> Result<QuantizedPalette> {
    let pixels = images
        .iter()
        .flat_map(|image| image.pixels())
        .filter(|pixel| pixel[3] >= ALPHA_CUTOFF)
        .map(|pixel| [pixel[0] as f64, pixel[1] as f64, pixel[2] as f64])
        .collect::<Vec<_>>();
    if pixels.is_empty() {
        bail!("all normalized avatars are transparent");
    }

    let mut histogram: HashMap<[u8; 3], ([u64; 3], u64)> = HashMap::new();
    for rgb in &pixels {
        let key = [rgb[0] as u8 >> 3, rgb[1] as u8 >> 3, rgb[2] as u8 >> 3];
        let entry = histogram.entry(key).or_insert(([0; 3], 0));
        entry.0[0] += rgb[0] as u64;
        entry.0[1] += rgb[1] as u64;
        entry.0[2] += rgb[2] as u64;
        entry.1 += 1;
    }
    let buckets = sorted_buckets(histogram);

    let color_count = PALETTE_LIMIT.min(buckets.len());
    let mut centroids = initial_centroids(&buckets, color_count);
    for _ in 0..16 {
        let mut sums = vec![[0.0; 3]; centroids.len()];
        let mut counts = vec![0u64; centroids.len()];
        for rgb in &pixels {
            let index = nearest(*rgb, &centroids);
            sums[index][0] += rgb[0];
            sums[index][1] += rgb[1];
            sums[index][2] += rgb[2];
            counts[index] += 1;
        }
        for (index, center) in centroids.iter_mut().enumerate() {
            if counts[index] != 0 {
                center[0] = sums[index][0] / counts[index] as f64;
                center[1] = sums[index][1] / counts[index] as f64;
                center[2] = sums[index][2] / counts[index] as f64;
            }
        }
    }

    let recolor_keys = [
        [0x4a, 0x2a, 0x1e],
        [0xf4, 0xc7, 0x9a],
        [0x3f, 0x7d, 0x45],
        [0x31, 0x4a, 0x6e],
    ];
    let mut palette = centroids
        .iter()
        .map(|center| {
            [
                center[0].round() as u8,
                center[1].round() as u8,
                center[2].round() as u8,
            ]
        })
        .collect::<Vec<_>>();
    for color in &mut palette {
        if recolor_keys.contains(color) {
            color[2] = color[2].saturating_add(1);
        }
    }
    Ok(QuantizedPalette {
        keys: avatar_palette_keys(color_count),
        colors: palette,
        centroids,
    })
}

fn load_existing_palette(path: &Path) -> Result<QuantizedPalette> {
    let source = fs::read_to_string(path)
        .with_context(|| format!("reading existing palette {}", path.display()))?;
    let root = toml::from_str::<toml::Table>(&source)
        .with_context(|| format!("parsing existing palette {}", path.display()))?;
    let table = root
        .get("palette")
        .and_then(toml::Value::as_table)
        .context("pack has no [palette] table")?;
    let mut keys = Vec::new();
    let mut colors = Vec::new();
    for (raw_key, value) in table {
        let mut chars = raw_key.chars();
        let Some(key) = chars.next() else {
            continue;
        };
        if chars.next().is_some() {
            continue;
        }
        let Some(raw_color) = value.as_str() else {
            continue;
        };
        let Some(hex) = raw_color.strip_prefix('#') else {
            continue;
        };
        if hex.len() != 6 {
            continue;
        }
        let color = [
            u8::from_str_radix(&hex[0..2], 16)?,
            u8::from_str_radix(&hex[2..4], 16)?,
            u8::from_str_radix(&hex[4..6], 16)?,
        ];
        keys.push(key);
        colors.push(color);
    }
    if keys.is_empty() {
        bail!("existing pack palette has no opaque single-character colors");
    }
    let centroids = colors
        .iter()
        .map(|color| [color[0] as f64, color[1] as f64, color[2] as f64])
        .collect();
    Ok(QuantizedPalette {
        keys,
        colors,
        centroids,
    })
}

fn prepare_output(output_dir: &Path) -> Result<OutputLayout> {
    fs::create_dir_all(output_dir).with_context(|| format!("creating {}", output_dir.display()))?;
    let preview = output_dir.join("preview");
    fs::create_dir_all(&preview).with_context(|| format!("creating {}", preview.display()))?;
    Ok(OutputLayout {
        root: output_dir.to_path_buf(),
        preview,
    })
}

fn write_palette_fragment(
    layout: &OutputLayout,
    header: &str,
    palette: &QuantizedPalette,
) -> Result<()> {
    let mut palette_toml = String::from(header);
    for (key, color) in palette.keys.iter().zip(&palette.colors) {
        palette_toml.push_str(&format!(
            "\"{key}\" = \"#{:02x}{:02x}{:02x}\"\n",
            color[0], color[1], color[2]
        ));
    }
    fs::write(
        layout.root.join("market_avatar_hires.palette.toml"),
        palette_toml,
    )
    .context("writing avatar palette fragment")
}

fn sprite_text(output: &SpriteOutput<'_>, palette: &QuantizedPalette) -> String {
    let source_name = output
        .source
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("avatar.png");
    let (canvas_w, canvas_h) = output.image.dimensions();
    let mut sprite = format!(
        "# Local-only derivative of {source_name}; fixed {canvas_w}x{canvas_h} high-resolution paperdoll canvas.\n@frame 0\n"
    );
    let mut nearest_cache = HashMap::<[u8; 3], char>::new();
    for row in output.image.rows() {
        for (x, pixel) in row.enumerate() {
            if x != 0 {
                sprite.push(' ');
            }
            if pixel[3] < ALPHA_CUTOFF {
                sprite.push('.');
            } else {
                let rgb = [pixel[0], pixel[1], pixel[2]];
                let key = *nearest_cache.entry(rgb).or_insert_with(|| {
                    let sample = [rgb[0] as f64, rgb[1] as f64, rgb[2] as f64];
                    palette.keys[nearest(sample, &palette.centroids)]
                });
                sprite.push(key);
            }
        }
        sprite.push('\n');
    }
    sprite
}

fn write_sprite_output(
    layout: &OutputLayout,
    output: SpriteOutput<'_>,
    palette: &QuantizedPalette,
) -> Result<()> {
    let sprite_path = layout.root.join(format!("{}.sprite", output.stem));
    fs::write(&sprite_path, sprite_text(&output, palette))
        .with_context(|| format!("writing {}", sprite_path.display()))?;
    let preview = image::imageops::resize(
        output.image,
        output.image.width() * PREVIEW_SCALE,
        output.image.height() * PREVIEW_SCALE,
        FilterType::Nearest,
    );
    let preview_path = layout.preview.join(format!("{}.png", output.stem));
    preview
        .save(&preview_path)
        .with_context(|| format!("writing {}", preview_path.display()))
}

fn write_outputs(output_dir: &Path, inputs: &[PathBuf], images: &[RgbaImage]) -> Result<()> {
    let layout = prepare_output(output_dir)?;
    let palette = quantize(images)?;
    write_palette_fragment(&layout, STATIC_PALETTE_HEADER, &palette)?;
    for (index, (source, image)) in inputs.iter().zip(images).enumerate() {
        write_sprite_output(
            &layout,
            SpriteOutput {
                source,
                image,
                stem: format!("market_avatar_hires_{index}"),
            },
            &palette,
        )?;
    }
    Ok(())
}

fn write_walk_outputs(output_dir: &Path, inputs: &[PathBuf], images: &[RgbaImage]) -> Result<()> {
    let layout = prepare_output(output_dir)?;
    let palette = quantize(images)?;
    write_palette_fragment(&layout, WALK_PALETTE_HEADER, &palette)?;
    for slot in 0..AVATAR_COUNT {
        let start = slot * WALK_SEQUENCE_FRAMES;
        write_sprite_output(
            &layout,
            SpriteOutput {
                source: &inputs[start],
                image: &images[start],
                stem: format!("market_avatar_hires_{slot}"),
            },
            &palette,
        )?;
        for pose in 0..WALK_POSES {
            let input_index = start + 1 + pose;
            write_sprite_output(
                &layout,
                SpriteOutput {
                    source: &inputs[input_index],
                    image: &images[input_index],
                    stem: format!("market_avatar_walk_hires_{}", slot * WALK_POSES + pose),
                },
                &palette,
            )?;
        }
    }
    Ok(())
}

fn write_market_outputs(output_dir: &Path, inputs: &[PathBuf], images: &[RgbaImage]) -> Result<()> {
    let layout = prepare_output(output_dir)?;
    let palette = quantize(images)?;
    write_palette_fragment(&layout, MARKET_PALETTE_HEADER, &palette)?;
    let batch = OutputBatch {
        layout: &layout,
        inputs,
        images,
        palette: &palette,
    };
    for slot in 0..AVATAR_COUNT {
        let start = slot * MARKET_SEQUENCE_FRAMES;
        batch.write_base(slot, start)?;
        for action in MARKET_ACTION_OUTPUTS {
            batch.write_action(slot, start, action)?;
        }
    }
    Ok(())
}

fn write_status_outputs(output_dir: &Path, inputs: &[PathBuf], images: &[RgbaImage]) -> Result<()> {
    let layout = prepare_output(output_dir)?;
    let palette = quantize(images)?;
    write_palette_fragment(&layout, STATUS_PALETTE_HEADER, &palette)?;
    let batch = OutputBatch {
        layout: &layout,
        inputs,
        images,
        palette: &palette,
    };
    for slot in 0..AVATAR_COUNT {
        let start = slot * STATUS_SEQUENCE_FRAMES;
        batch.write_base(slot, start)?;
        for action in STATUS_ACTION_OUTPUTS {
            batch.write_action(slot, start, action)?;
        }
    }
    Ok(())
}

fn write_combat_outputs(
    output_dir: &Path,
    palette_path: &Path,
    inputs: &[PathBuf],
    images: &[RgbaImage],
) -> Result<()> {
    let layout = prepare_output(output_dir)?;
    let palette = load_existing_palette(palette_path)?;
    let batch = OutputBatch {
        layout: &layout,
        inputs,
        images,
        palette: &palette,
    };
    for slot in 0..AVATAR_COUNT {
        let start = slot * COMBAT_SEQUENCE_FRAMES;
        batch.write_action(slot, start, COMBAT_SWING_OUTPUT)?;
    }
    Ok(())
}

fn write_skill_effect_outputs(
    output_dir: &Path,
    palette_path: &Path,
    inputs: &[PathBuf],
    images: &[RgbaImage],
) -> Result<()> {
    let layout = prepare_output(output_dir)?;
    let palette = load_existing_palette(palette_path)?;
    for (index, (source, image)) in inputs.iter().zip(images).enumerate() {
        write_sprite_output(
            &layout,
            SpriteOutput {
                source,
                image,
                stem: format!("training_skill_magic_claw_{index}"),
            },
            &palette,
        )?;
    }
    Ok(())
}

fn parse_args() -> Result<(QuantizeMode, PathBuf, Option<PathBuf>, Vec<PathBuf>)> {
    let mut args = env::args_os().skip(1).collect::<Vec<_>>();
    let mode = match args.first().and_then(|arg| arg.to_str()) {
        Some("--walk-cycle") => {
            args.remove(0);
            QuantizeMode::WalkCycle
        }
        Some("--market-cycle") => {
            args.remove(0);
            QuantizeMode::MarketCycle
        }
        Some("--status-cycle") => {
            args.remove(0);
            QuantizeMode::StatusCycle
        }
        Some("--combat-cycle") => {
            args.remove(0);
            QuantizeMode::CombatCycle
        }
        Some("--skill-effect") => {
            args.remove(0);
            QuantizeMode::SkillEffect
        }
        _ => QuantizeMode::Static,
    };
    let output_dir = PathBuf::from(args.first().cloned().context(
        "usage: avatar_quantize [--walk-cycle|--market-cycle|--status-cycle] <output-dir> <avatar images...> | [--combat-cycle|--skill-effect] <output-dir> <pack.toml> <images...>",
    )?);
    args.remove(0);
    let palette_path = if matches!(mode, QuantizeMode::CombatCycle | QuantizeMode::SkillEffect) {
        let path =
            PathBuf::from(args.first().cloned().context(
                "--combat-cycle and --skill-effect need the existing pack.toml after the output directory",
            )?);
        args.remove(0);
        Some(path)
    } else {
        None
    };
    let inputs = args.into_iter().map(PathBuf::from).collect::<Vec<_>>();
    let expected = mode.expected_inputs();
    if inputs.len() != expected {
        bail!(
            "usage: avatar_quantize [--walk-cycle|--market-cycle|--status-cycle] <output-dir> <avatar images...> | [--combat-cycle|--skill-effect] <output-dir> <pack.toml> <images...> (need {expected}, got {})",
            inputs.len()
        );
    }
    Ok((mode, output_dir, palette_path, inputs))
}

fn load_sources(inputs: &[PathBuf]) -> Result<Vec<RgbaImage>> {
    inputs
        .iter()
        .map(|path| {
            Ok(image::open(path)
                .with_context(|| format!("decoding {}", path.display()))?
                .to_rgba8())
        })
        .collect()
}

fn normalize_inputs(
    mode: QuantizeMode,
    inputs: &[PathBuf],
    sources: &[RgbaImage],
) -> Result<Vec<RgbaImage>> {
    match mode {
        QuantizeMode::Static => sources
            .iter()
            .zip(inputs)
            .map(|(source, path)| {
                normalize_avatar(source).with_context(|| format!("normalizing {}", path.display()))
            })
            .collect(),
        QuantizeMode::WalkCycle => {
            let mut normalized = Vec::with_capacity(sources.len());
            for sequence in sources.chunks_exact(WALK_SEQUENCE_FRAMES) {
                normalized.extend(normalize_avatar_sequence(sequence)?);
            }
            Ok(normalized)
        }
        QuantizeMode::MarketCycle => {
            let mut normalized = Vec::with_capacity(sources.len());
            for sequence in sources.chunks_exact(MARKET_SEQUENCE_FRAMES) {
                normalized.extend(normalize_avatar_sequence(sequence)?);
            }
            Ok(normalized)
        }
        QuantizeMode::StatusCycle => {
            let mut normalized = Vec::with_capacity(sources.len());
            for sequence in sources.chunks_exact(STATUS_SEQUENCE_FRAMES) {
                normalized.extend(normalize_avatar_sequence(sequence)?);
            }
            Ok(normalized)
        }
        QuantizeMode::CombatCycle => {
            let mut normalized = Vec::with_capacity(sources.len());
            for sequence in sources.chunks_exact(COMBAT_SEQUENCE_FRAMES) {
                normalized.extend(normalize_combat_sequence(sequence)?);
            }
            Ok(normalized)
        }
        QuantizeMode::SkillEffect => normalize_magic_claw_frames(sources),
    }
}

fn normalize_magic_claw_frames(sources: &[RgbaImage]) -> Result<Vec<RgbaImage>> {
    if sources.len() != MAGIC_CLAW_FRAME_SIZES.len() {
        bail!(
            "Magic Claw needs {} frames, got {}",
            MAGIC_CLAW_FRAME_SIZES.len(),
            sources.len()
        );
    }

    sources
        .iter()
        .zip(MAGIC_CLAW_FRAME_SIZES)
        .zip(MAGIC_CLAW_ORIGINS)
        .enumerate()
        .map(|(index, ((source, expected_size), (origin_x, origin_y)))| {
            if source.dimensions() != expected_size {
                bail!(
                    "Magic Claw frame {index} expected {}x{}, got {}x{}",
                    expected_size.0,
                    expected_size.1,
                    source.width(),
                    source.height()
                );
            }
            let x = MAGIC_CLAW_CANVAS_ORIGIN_X
                .checked_sub(origin_x)
                .context("Magic Claw x origin does not fit the shared canvas")?;
            let y = MAGIC_CLAW_CANVAS_ORIGIN_Y
                .checked_sub(origin_y)
                .context("Magic Claw y origin does not fit the shared canvas")?;
            if x + source.width() > MAGIC_CLAW_CANVAS_W || y + source.height() > MAGIC_CLAW_CANVAS_H
            {
                bail!("Magic Claw frame {index} exceeds the shared canvas");
            }
            let mut canvas =
                RgbaImage::from_pixel(MAGIC_CLAW_CANVAS_W, MAGIC_CLAW_CANVAS_H, Rgba([0, 0, 0, 0]));
            image::imageops::overlay(&mut canvas, source, i64::from(x), i64::from(y));
            Ok(canvas)
        })
        .collect()
}

fn main() -> Result<()> {
    let (mode, output_dir, palette_path, inputs) = parse_args()?;
    let sources = load_sources(&inputs)?;
    let images = normalize_inputs(mode, &inputs, &sources)?;
    match mode {
        QuantizeMode::Static => write_outputs(&output_dir, &inputs, &images)?,
        QuantizeMode::WalkCycle => write_walk_outputs(&output_dir, &inputs, &images)?,
        QuantizeMode::MarketCycle => write_market_outputs(&output_dir, &inputs, &images)?,
        QuantizeMode::StatusCycle => write_status_outputs(&output_dir, &inputs, &images)?,
        QuantizeMode::CombatCycle => write_combat_outputs(
            &output_dir,
            palette_path
                .as_deref()
                .expect("combat parsing requires an existing palette"),
            &inputs,
            &images,
        )?,
        QuantizeMode::SkillEffect => write_skill_effect_outputs(
            &output_dir,
            palette_path
                .as_deref()
                .expect("skill-effect parsing requires an existing palette"),
            &inputs,
            &images,
        )?,
    }
    println!("inputs={}", inputs.len());
    let (canvas_w, canvas_h) = match mode {
        QuantizeMode::CombatCycle => (COMBAT_CANVAS_W, COMBAT_CANVAS_H),
        QuantizeMode::SkillEffect => (MAGIC_CLAW_CANVAS_W, MAGIC_CLAW_CANVAS_H),
        _ => (CANVAS_W, CANVAS_H),
    };
    println!("canvas={canvas_w}x{canvas_h}");
    println!("output={}", output_dir.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn status_cycle_accepts_sixteen_official_frames_per_avatar() {
        assert_eq!(
            QuantizeMode::StatusCycle.expected_inputs(),
            8 * 16,
            "stand1, walk1, ladder, stand2, sit, and alert must share one transform per avatar"
        );
    }

    #[test]
    fn combat_cycle_adds_three_official_swing_frames_per_avatar() {
        assert_eq!(
            QuantizeMode::CombatCycle.expected_inputs(),
            8 * 19,
            "the sixteen stable body frames establish scale before three swingO1 frames"
        );
    }

    #[test]
    fn skill_effect_mode_accepts_the_four_official_magic_claw_frames() {
        assert_eq!(QuantizeMode::SkillEffect.expected_inputs(), 4);
    }

    #[test]
    fn magic_claw_frames_share_one_origin_normalized_canvas() {
        let mut sources = Vec::new();
        for (index, &(width, height)) in MAGIC_CLAW_FRAME_SIZES.iter().enumerate() {
            let mut frame = RgbaImage::from_pixel(width, height, Rgba([0, 0, 0, 0]));
            frame.put_pixel(0, 0, Rgba([20 + index as u8, 120, 255, 255]));
            sources.push(frame);
        }

        let normalized = normalize_magic_claw_frames(&sources)
            .expect("the four source-authored frames fit the shared origin canvas");
        assert_eq!(normalized.len(), 4);
        for frame in &normalized {
            assert_eq!(
                frame.dimensions(),
                (MAGIC_CLAW_CANVAS_W, MAGIC_CLAW_CANVAS_H)
            );
        }
        for (frame, &(origin_x, origin_y)) in normalized.iter().zip(&MAGIC_CLAW_ORIGINS) {
            assert!(
                frame.get_pixel(
                    MAGIC_CLAW_CANVAS_ORIGIN_X - origin_x,
                    MAGIC_CLAW_CANVAS_ORIGIN_Y - origin_y,
                )[3] >= ALPHA_CUTOFF
            );
        }
    }

    #[test]
    fn combat_canvas_keeps_the_character_baseline_and_extra_effect_margin() {
        let mut source = RgbaImage::from_pixel(20, 20, Rgba([0, 0, 0, 0]));
        for y in 4..20 {
            for x in 7..13 {
                source.put_pixel(x, y, Rgba([220, 150, 90, 255]));
            }
        }
        source.put_pixel(0, 1, Rgba([80, 180, 255, 255]));
        let transform = ImageTransform::from_bounds(7, 4, 12, 19);
        let combat = apply_combat_transform(&source, transform);
        let bounds = alpha_bounds(&combat).expect("combat frame remains visible");

        assert_eq!(combat.dimensions(), (COMBAT_CANVAS_W, COMBAT_CANVAS_H));
        assert_eq!(
            bounds.3,
            COMBAT_CANVAS_H - 1,
            "feet keep the shared baseline"
        );
        assert!(
            bounds.0 < (COMBAT_CANVAS_W - CANVAS_W) / 2 + transform.offset_x,
            "the larger canvas retains effect pixels left of the body content"
        );
    }

    #[test]
    fn normalize_avatar_uses_a_fixed_bottom_centred_canvas() {
        let mut source = RgbaImage::from_pixel(10, 10, Rgba([0, 0, 0, 0]));
        for y in 1..5 {
            for x in 2..4 {
                source.put_pixel(x, y, Rgba([200, 100, 50, 255]));
            }
        }

        let normalized = normalize_avatar(&source).expect("opaque source");
        assert_eq!(
            normalized.dimensions(),
            (96, 72),
            "the 720x480 market must retain one source pixel per displayed paperdoll pixel"
        );
        assert_eq!(normalized.dimensions(), (CANVAS_W, CANVAS_H));
        let bounds = alpha_bounds(&normalized).expect("normalized avatar remains opaque");
        assert_eq!(bounds.3, CANVAS_H - 1, "feet touch the shared baseline");
        assert_eq!(
            bounds.0 + bounds.2 + 1,
            CANVAS_W,
            "content has equal left/right transparent margins"
        );
    }

    #[test]
    fn walk_cycle_uses_one_body_crop_and_clips_distant_skill_effects() {
        let transparent = Rgba([0, 0, 0, 0]);
        let body = Rgba([200, 100, 50, 255]);
        let effect = Rgba([20, 80, 240, 255]);
        let mut stand = RgbaImage::from_pixel(64, 48, transparent);
        for y in 8..40 {
            for x in 26..36 {
                stand.put_pixel(x, y, body);
            }
        }
        let mut walk = stand.clone();
        for y in 18..30 {
            for x in 56..63 {
                walk.put_pixel(x, y, effect);
            }
        }
        let frames = vec![stand, walk.clone(), walk.clone(), walk.clone(), walk];

        let normalized = normalize_avatar_sequence(&frames).expect("five-frame avatar sequence");
        assert_eq!(normalized.len(), 5);
        let stand_bounds = alpha_bounds(&normalized[0]).expect("stand body");
        for frame in &normalized[1..] {
            assert_eq!(
                alpha_bounds(frame).expect("walk body"),
                stand_bounds,
                "a common source transform keeps an unchanged body pixel-perfect across frames"
            );
            assert!(
                frame.pixels().all(|pixel| *pixel != effect),
                "a far-away skill effect must not shrink or displace the paperdoll"
            );
        }
    }

    #[test]
    fn standing_skill_effect_does_not_shrink_the_character_body() {
        let transparent = Rgba([0, 0, 0, 0]);
        let body = Rgba([200, 100, 50, 255]);
        let effect = Rgba([20, 80, 240, 255]);
        let mut stand = RgbaImage::from_pixel(300, 300, transparent);
        for y in 120..220 {
            for x in 125..175 {
                stand.put_pixel(x, y, body);
            }
        }
        // Ranking renders can include a large aura/pet beside stand1 itself.
        // That decoration must not become the common crop authority, otherwise
        // the same-sized body is visibly miniaturised on upper platforms.
        for y in 70..170 {
            for x in 10..80 {
                stand.put_pixel(x, y, effect);
            }
        }
        let frames = vec![
            stand.clone(),
            stand.clone(),
            stand.clone(),
            stand.clone(),
            stand,
        ];

        let normalized = normalize_avatar_sequence(&frames).expect("effect-bearing stand sequence");
        let first = &normalized[0];
        let body_pixels = first.pixels().filter(|pixel| **pixel == body).count();

        assert!(
            first.pixels().all(|pixel| *pixel != effect),
            "stand1 decorations outside the body window must be clipped"
        );
        assert!(
            body_pixels >= 1_500,
            "the 50x100 body must retain a readable on-canvas scale; got {body_pixels} pixels"
        );
    }

    #[test]
    fn effect_heavy_stand_uses_the_character_foot_corridor_for_scale() {
        let transparent = Rgba([0, 0, 0, 0]);
        let body = Rgba([200, 100, 50, 255]);
        let effect = Rgba([20, 80, 240, 255]);
        let mut stand = RgbaImage::from_pixel(300, 300, transparent);
        // Mirrors the problematic public look: a large sun overlaps the
        // centre line while a heart extends below and left of the feet. The
        // character is composited above those effects by the public renderer.
        for y in 75..150 {
            for x in 145..220 {
                stand.put_pixel(x, y, effect);
            }
        }
        for y in 170..220 {
            for x in 105..135 {
                stand.put_pixel(x, y, effect);
            }
        }
        for y in 125..205 {
            for x in 125..165 {
                stand.put_pixel(x, y, body);
            }
        }
        let mut ladder = RgbaImage::from_pixel(300, 300, transparent);
        for y in 130..210 {
            for x in 128..168 {
                ladder.put_pixel(x, y, body);
            }
        }
        let frames = vec![
            stand.clone(),
            stand.clone(),
            stand.clone(),
            stand.clone(),
            stand.clone(),
            stand.clone(),
            stand,
            ladder.clone(),
            ladder,
        ];

        let transform = sequence_transform(&frames).expect("effect-heavy market sequence");
        let normalized = normalize_avatar_sequence(&frames).expect("normalized market sequence");
        let body_pixels = normalized[0]
            .pixels()
            .filter(|pixel| **pixel == body)
            .count();

        assert!(
            transform.crop_w <= 72,
            "effect-heavy crop width was {}",
            transform.crop_w
        );
        assert!(
            transform.crop_h <= 90,
            "effect-heavy crop height was {}",
            transform.crop_h
        );
        assert!(
            body_pixels >= 1_800,
            "the action character must remain crisp despite attached effects; got {body_pixels} body pixels"
        );
    }

    #[test]
    fn equal_frequency_palette_buckets_have_a_stable_rgb_tie_breaker() {
        // 2026-08-04: two v0.8 generations from identical PNGs drifted in 33
        // text-asset hashes because equal-count HashMap buckets had no tie-break.
        let colors = [
            ([3, 1, 2], ([30, 10, 20], 10)),
            ([1, 3, 2], ([10, 30, 20], 10)),
            ([2, 1, 3], ([20, 10, 30], 10)),
            ([0, 0, 0], ([0, 0, 0], 20)),
        ];
        let forward = colors.into_iter().collect::<HashMap<_, _>>();
        let reverse = colors.into_iter().rev().collect::<HashMap<_, _>>();
        let forward_keys = sorted_buckets(forward)
            .into_iter()
            .map(|bucket| bucket.key)
            .collect::<Vec<_>>();
        let reverse_keys = sorted_buckets(reverse)
            .into_iter()
            .map(|bucket| bucket.key)
            .collect::<Vec<_>>();

        assert_eq!(forward_keys, reverse_keys);
        assert_eq!(
            forward_keys,
            vec![[0, 0, 0], [1, 3, 2], [2, 1, 3], [3, 1, 2]]
        );
    }
}
